# docker-compose.yml created by chen
#
# backend: 4040 -> 13100
# 算法: 8000 -> 14000
version: '2'
services:
  pai-backend:
    image: registry.cn-shanghai.aliyuncs.com/cbb_registry/pai-backend:<BUILD_TAG>
    ports:
      - "13100:4040"
    restart: always
    volumes:
      - /opt/jenkins/data:/tmp