# docker-compose.yml created by chen
# 4040 -> 13100
version: '2'
services:
  pai-backend:
    image: registry.cn-shanghai.aliyuncs.com/cbb_registry/pai-backend:<BUILD_TAG>
    ports:
      - "13100:4040"